{% set name = "ete4" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ete4-{{ version }}.tar.gz
  sha256: 83c44adee04edb5bfe6ec642a29e22c92d8ccb46a10d4a292483d586acbb5f6c

build:
  skip: true  # [py<37 or win]
  entry_points:
    - ete4 = ete4.tools.ete:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=61.0
    - cython
    - pip
  run:
    - python
    - bottle
    - brotli
    - numpy
    - scipy
    - requests

test:
  imports:
    - ete4
  commands:
    - pip check
    - ete4 --help
  requires:
    - pip

about:
  home: https://etetoolkit.org
  summary: A Python Environment for (phylogenetic) Tree Exploration
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mschilli87
