{% set name = "ete4" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ete4-{{ version }}.tar.gz
  sha256: c063588a9c77aa16a3de93de4d2016afae0236d4daf325d6290ed668d15a4b86

build:
  skip: true  # [py<37 or win]
  entry_points:
    - ete4 = ete4.tools.ete:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=61.0
    - cython
    - pip
  run:
    - python
    - bottle
    - brotli
    - numpy
    - scipy
    - requests

test:
  imports:
    - ete4
  commands:
    - pip check
    - ete4 --help
  requires:
    - pip

about:
  home: https://etetoolkit.org
  summary: A Python Environment for (phylogenetic) Tree Exploration
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mschilli87
